require('dotenv').config();
const { sequelize } = require('./database');
const { User, Car } = require('../models/index');

const cars = [
  {
    brand: 'BMW',
    model: 'E30 M3 Sport Evolution',
    year: 1990,
    trim: 'Sport Evolution',
    price: 85000,
    originalPrice: 95000,
    condition: 'used',
    mileage: 62000,
    modelType: 'sedan',
    color: 'White',
    city: 'Cairo',
    location: 'Heliopolis, Cairo',
    fuelType: 'gasoline',
    transmission: 'manual',
    driveType: 'rwd',
    engineSize: '2.3L',
    horsepower: 238,
    doors: 2,
    seats: 4,
    model3dUrl: 'https://res.cloudinary.com/bedo/image/upload/v1780898038/compressed_1990_bmw_e30_m3_sport_evolution_swew3l.glb',
    description: 'Iconic 1990 BMW E30 M3 Sport Evolution — one of the most legendary sports cars ever built. Collector condition.',
    features: ['Manual Gearbox', 'Sport Seats', 'Limited Slip Differential', 'Sport Suspension', 'M Badge'],
    rating: 4.9,
    isFeatured: true,
    status: 'available',
  },
  {
    brand: 'Mercedes-Benz',
    model: 'GLE63 AMG Coupe',
    year: 2016,
    trim: 'AMG Coupe',
    price: 72000,
    originalPrice: 80000,
    condition: 'used',
    mileage: 45000,
    modelType: 'suv',
    color: 'Black',
    city: 'Cairo',
    location: 'New Cairo, Cairo',
    fuelType: 'gasoline',
    transmission: 'automatic',
    driveType: 'awd',
    engineSize: '5.5L',
    horsepower: 577,
    doors: 4,
    seats: 5,
    model3dUrl: 'https://res.cloudinary.com/bedo/image/upload/v1780898101/compressed_2016_mercedes-benz_gle63_amg_coupe_ahcbt8.glb',
    description: 'Mercedes-Benz GLE63 AMG Coupe 2016 — brutal V8 power with luxury SUV comfort. Full AMG package.',
    features: ['AMG Performance Package', 'Panoramic Roof', 'Leather Seats', 'Burmester Audio', '360 Camera', 'Keyless Entry', 'Heated Seats', 'Blind Spot Monitor'],
    rating: 4.8,
    isFeatured: true,
    status: 'available',
  },
  {
    brand: 'Porsche',
    model: 'Carrera GT',
    year: 2004,
    trim: 'Carrera GT',
    price: 850000,
    originalPrice: 900000,
    condition: 'used',
    mileage: 12000,
    modelType: 'coupe',
    color: 'Silver',
    city: 'Cairo',
    location: 'Zamalek, Cairo',
    fuelType: 'gasoline',
    transmission: 'manual',
    driveType: 'rwd',
    engineSize: '5.7L V10',
    horsepower: 612,
    doors: 2,
    seats: 2,
    model3dUrl: 'https://res.cloudinary.com/bedo/image/upload/v1780898085/compressed_2004_porsche_carrera_gt_uhquxg.glb',
    description: 'Ultra rare 2004 Porsche Carrera GT — one of the greatest supercars ever made. V10 naturally aspirated engine, carbon fibre body.',
    features: ['V10 Engine', 'Carbon Fibre Body', 'Ceramic Brakes', 'Sport Exhaust', 'Racing Seats', 'Manual Gearbox'],
    rating: 5.0,
    isFeatured: true,
    status: 'available',
  },
  {
    brand: 'Mercedes-Benz',
    model: 'E55 AMG W211',
    year: 2003,
    trim: 'AMG',
    price: 35000,
    originalPrice: 40000,
    condition: 'used',
    mileage: 90000,
    modelType: 'sedan',
    color: 'Black',
    city: 'Alexandria',
    location: 'Smouha, Alexandria',
    fuelType: 'gasoline',
    transmission: 'automatic',
    driveType: 'rwd',
    engineSize: '5.4L V8',
    horsepower: 476,
    doors: 4,
    seats: 5,
    model3dUrl: 'https://res.cloudinary.com/bedo/image/upload/v1780898063/compressed_2003_mercedes-benz_e55_amg_w211_xdzsdy.glb',
    description: 'Classic 2003 Mercedes-Benz E55 AMG W211 — the supercharged V8 sleeper. Legendary AMG performance in an elegant sedan.',
    features: ['Supercharged V8', 'AMG Sport Package', 'Leather Seats', 'Sunroof', 'Sport Exhaust', 'Bose Audio'],
    rating: 4.7,
    isFeatured: false,
    status: 'available',
  },
  {
    brand: 'BMW',
    model: 'i8 ACS8',
    year: 2017,
    trim: 'AC Schnitzer ACS8',
    price: 95000,
    originalPrice: 110000,
    condition: 'used',
    mileage: 22000,
    modelType: 'coupe',
    color: 'Blue',
    city: 'Cairo',
    location: 'Maadi, Cairo',
    fuelType: 'plug_in_hybrid',
    transmission: 'automatic',
    driveType: 'awd',
    engineSize: '1.5L Hybrid',
    horsepower: 374,
    doors: 2,
    seats: 4,
    model3dUrl: 'https://res.cloudinary.com/bedo/image/upload/v1780898121/compressed_2017_ac_schnitzer_bmw_i8_acs8_k4lfuy.glb',
    description: 'Stunning 2017 BMW i8 with AC Schnitzer ACS8 package — futuristic hybrid supercar with butterfly doors and incredible performance.',
    features: ['Butterfly Doors', 'Hybrid System', 'Carbon Fibre', 'Heads Up Display', 'Harman Kardon Audio', 'Lane Assist', 'Wireless Charging', 'Apple CarPlay'],
    rating: 4.8,
    isFeatured: true,
    status: 'available',
  },
  {
    brand: 'Volkswagen',
    model: 'Golf GTI',
    year: 2020,
    trim: 'GTI',
    price: 28000,
    originalPrice: 32000,
    condition: 'used',
    mileage: 38000,
    modelType: 'sedan',
    color: 'Red',
    city: 'Giza',
    location: '6th October, Giza',
    fuelType: 'gasoline',
    transmission: 'automatic',
    driveType: 'fwd',
    engineSize: '2.0T',
    horsepower: 241,
    doors: 4,
    seats: 5,
    model3dUrl: 'https://res.cloudinary.com/bedo/image/upload/v1780898145/compressed_2020_volkswagen_golf_gti_lrhpnk.glb',
    description: 'VW Golf GTI 2020 — the perfect hot hatch. Fun, practical, and fast. Full GTI package with DSG gearbox.',
    features: ['DSG Gearbox', 'Sport Seats', 'Apple CarPlay', 'Android Auto', 'Parking Sensors', 'Backup Camera', 'Adaptive Cruise Control', 'Lane Assist'],
    rating: 4.6,
    isFeatured: false,
    status: 'available',
  },
  {
    brand: 'Audi',
    model: 'SQ8 e-tron',
    year: 2023,
    trim: 'SQ8 e-tron',
    price: 110000,
    originalPrice: 120000,
    condition: 'new',
    mileage: 0,
    modelType: 'suv',
    color: 'Gray',
    city: 'Cairo',
    location: 'New Cairo, Cairo',
    fuelType: 'electric',
    transmission: 'automatic',
    driveType: 'awd',
    engineSize: 'Electric',
    horsepower: 503,
    doors: 4,
    seats: 5,
    model3dUrl: 'https://res.cloudinary.com/bedo/image/upload/v1780898286/compressed_2023_audi_sq8_e_tron_gxrghx.glb',
    description: 'All-new 2023 Audi SQ8 e-tron — Audi\'s flagship electric SUV with tri-motor setup and 503hp. Zero emissions, maximum luxury.',
    features: ['Tri-Motor Electric', 'Panoramic Roof', 'Matrix LED Headlights', 'Bang & Olufsen Audio', '360 Camera', 'Adaptive Air Suspension', 'Wireless Charging', 'Virtual Cockpit', 'Keyless Entry'],
    rating: 4.9,
    isFeatured: true,
    status: 'available',
  },
  {
    brand: 'Honda',
    model: 'Acty HA3',
    year: 1992,
    trim: 'HA3',
    price: 8500,
    originalPrice: 10000,
    condition: 'used',
    mileage: 75000,
    modelType: 'truck',
    color: 'White',
    city: 'Cairo',
    location: 'Shubra, Cairo',
    fuelType: 'gasoline',
    transmission: 'manual',
    driveType: '4wd',
    engineSize: '0.66L',
    horsepower: 38,
    doors: 2,
    seats: 2,
    model3dUrl: 'https://res.cloudinary.com/bedo/image/upload/v1780907103/compressed_ac_-_honda_acty_ha3_free_fagapo.glb',
    description: 'Classic Honda Acty HA3 Kei truck — ultra reliable Japanese mini truck. Perfect for city deliveries and small businesses.',
    features: ['4WD', 'Manual Gearbox', 'Flatbed', 'Fuel Efficient'],
    rating: 4.2,
    isFeatured: false,
    status: 'available',
  },
  {
    brand: 'Dodge',
    model: 'Durango SRT 392',
    year: 2021,
    trim: 'SRT 392',
    price: 68000,
    originalPrice: 75000,
    condition: 'used',
    mileage: 25000,
    modelType: 'suv',
    color: 'Black',
    city: 'Cairo',
    location: 'Heliopolis, Cairo',
    fuelType: 'gasoline',
    transmission: 'automatic',
    driveType: 'awd',
    engineSize: '6.4L V8',
    horsepower: 475,
    doors: 4,
    seats: 7,
    model3dUrl: 'https://res.cloudinary.com/bedo/image/upload/v1780898390/compressed_dodge_durango_srt_392_azm4lf.glb',
    description: 'Dodge Durango SRT 392 2021 — the most powerful 3-row SUV ever. 6.4L HEMI V8 with 475hp. Family meets muscle.',
    features: ['6.4L HEMI V8', 'SRT Performance Package', 'Laguna Leather Seats', 'Beats Audio', 'Panoramic Roof', '360 Camera', 'Adaptive Damping', 'Launch Control', 'Heated Seats'],
    rating: 4.7,
    isFeatured: true,
    status: 'available',
  },
  {
    brand: 'Cadillac',
    model: 'Escalade Premium',
    year: 2022,
    trim: 'Premium Luxury',
    price: 95000,
    originalPrice: 105000,
    condition: 'used',
    mileage: 18000,
    modelType: 'suv',
    color: 'White',
    city: 'Alexandria',
    location: 'Miami, Alexandria',
    fuelType: 'gasoline',
    transmission: 'automatic',
    driveType: 'awd',
    engineSize: '6.2L V8',
    horsepower: 420,
    doors: 4,
    seats: 7,
    model3dUrl: 'https://res.cloudinary.com/bedo/image/upload/v1780898308/compressed_cadillac_escalade_premium_u5jrmb.glb',
    description: 'Cadillac Escalade Premium 2022 — the pinnacle of American luxury SUVs. Massive OLED dashboard, premium sound, and V8 power.',
    features: ['OLED Dashboard', 'AKG Audio System', 'Panoramic Roof', 'Magnetic Ride Control', 'Super Cruise', 'Night Vision', '360 Camera', 'Massage Seats', 'Wireless Charging', 'Remote Start'],
    rating: 4.8,
    isFeatured: true,
    status: 'available',
  },
  {
    brand: 'McLaren',
    model: 'P1',
    year: 2015,
    trim: 'P1',
    price: 1500000,
    originalPrice: 1600000,
    condition: 'used',
    mileage: 5000,
    modelType: 'coupe',
    color: 'Orange',
    city: 'Cairo',
    location: 'Zamalek, Cairo',
    fuelType: 'plug_in_hybrid',
    transmission: 'automatic',
    driveType: 'rwd',
    engineSize: '3.8L V8 Hybrid',
    horsepower: 903,
    doors: 2,
    seats: 2,
    model3dUrl: 'https://res.cloudinary.com/bedo/image/upload/v1780907111/compressed_ac_-_mclaren_p1_free_fhaxeo.glb',
    description: 'The legendary McLaren P1 — one of the holy trinity of hypercars. 903hp hybrid system, active aerodynamics, and breathtaking performance.',
    features: ['903hp Hybrid System', 'Active Aerodynamics', 'Carbon Fibre Monocoque', 'Dihedral Doors', 'Race Mode', 'Ceramic Brakes', 'Sport Exhaust', 'Carbon Ceramic Discs'],
    rating: 5.0,
    isFeatured: true,
    status: 'available',
  },
  {
    brand: 'Concept',
    model: 'Free Concept Car 037',
    year: 2024,
    trim: 'Concept',
    price: 250000,
    originalPrice: 280000,
    condition: 'new',
    mileage: 0,
    modelType: 'coupe',
    color: 'Silver',
    city: 'Cairo',
    location: 'New Cairo, Cairo',
    fuelType: 'electric',
    transmission: 'automatic',
    driveType: 'awd',
    engineSize: 'Electric',
    horsepower: 600,
    doors: 2,
    seats: 2,
    model3dUrl: 'https://res.cloudinary.com/bedo/image/upload/v1780907172/compressed_free_concept_car_037_-_public_domain_cc0_sesyws.glb',
    description: 'Futuristic 2024 concept electric coupe — a glimpse into the future of automotive design. Fully electric with 600hp.',
    features: ['Full Electric', 'Augmented Reality Dashboard', 'Autonomous Driving', 'Gullwing Doors', 'Facial Recognition', 'Holographic Display'],
    rating: 4.9,
    isFeatured: true,
    status: 'available',
  },
  {
    brand: 'Sci-Fi',
    model: 'Vehicle 029',
    year: 2025,
    trim: 'Concept',
    price: 500000,
    originalPrice: 550000,
    condition: 'new',
    mileage: 0,
    modelType: 'coupe',
    color: 'Black',
    city: 'Cairo',
    location: 'New Cairo, Cairo',
    fuelType: 'electric',
    transmission: 'automatic',
    driveType: 'awd',
    engineSize: 'Electric',
    horsepower: 1000,
    doors: 2,
    seats: 2,
    model3dUrl: 'https://res.cloudinary.com/bedo/image/upload/v1780907177/compressed_free_sci-fi_vehicle_029_-_public_domain_cc0_j9d0qm.glb',
    description: 'Sci-Fi concept vehicle 2025 — beyond conventional automotive design. 1000hp electric powertrain with futuristic styling.',
    features: ['1000hp Electric', 'AI Autopilot', 'Holographic Controls', 'Transparent Roof', 'Magnetic Suspension', 'Biometric Access'],
    rating: 5.0,
    isFeatured: true,
    status: 'available',
  },
];

async function seed() {
  try {
    await sequelize.authenticate();
    console.log('✅ Database connected');
    await sequelize.sync({ alter: true });
    console.log('✅ Models synced');

    // Create or find admin user
    let admin = await User.findOne({ where: { email: 'admin@carstore.com' } });
    if (!admin) {
      admin = await User.create({
        email: 'admin@carstore.com',
        password: 'admin123456',
        firstName: 'Admin',
        lastName: 'CarStore',
        role: 'admin',
        isEmailVerified: true,
        authProvider: 'local',
      });
      console.log('✅ Admin created — admin@carstore.com / admin123456');
    } else {
      console.log('✅ Admin already exists');
    }

    // Delete existing cars to avoid duplicates
    await Car.destroy({ where: { sellerId: admin.id } });
    console.log('🗑️  Cleared old cars');

    // Create all cars
    let count = 0;
    for (const car of cars) {
      await Car.create({ ...car, sellerId: admin.id });
      count++;
      console.log(`✅ [${count}/${cars.length}] ${car.brand} ${car.model} (${car.year})`);
    }

    console.log(`\n🚗 Done! ${count} cars added to database`);
    console.log('👤 Admin: admin@carstore.com / admin123456');
    process.exit(0);
  } catch (error) {
    console.error('❌ Seed failed:', error.message);
    process.exit(1);
  }
}

seed();
